# ========================================
# DOCKER COMPOSE - PRODUCCIÓN
# ========================================
# Backend: Puerto 5000 (Gunicorn)
# Web: Puerto 8080 (Nginx + React build)
# Acceso externo: https://app.nioxtec.es
# ========================================

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Ensure production behavior in container
      FLASK_ENV: production
      PORT: 5000
      WKHTMLTOPDF_PATH: /usr/bin/wkhtmltopdf
      FORCE_HTTPS: "false"
    volumes:
      # Persist database and client documents (instance/)
      - ./instance:/app/instance
      # Persist generated files (PDFs, downloads)
      - ./downloads:/app/downloads
      # Persist product images and dynamic uploads
      - ./static/uploads:/app/static/uploads
    ports:
      # Exponer solo en loopback del host (Cloudflared accede a localhost)
      - "127.0.0.1:5000:5000"
    networks:
      - app_net

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      # Exponer solo en loopback del host (Cloudflared accede a localhost)
      - "127.0.0.1:8080:8080"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

