version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: nioxtec
      POSTGRES_USER: niox
      POSTGRES_PASSWORD: nioxpass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: python:3.13-slim
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgresql+psycopg://niox:nioxpass@db:5432/nioxtec
      FLASK_DEBUG: "0"
      JWT_SECRET_KEY: super-secret-change
      CORS_ORIGINS: http://localhost
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
    depends_on:
      - db
    command: bash -lc "pip install --no-cache-dir -r requirements.txt && gunicorn -w 3 -b 0.0.0.0:5000 app:app"
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  db_data:


