name: Auto PR from release to main

on:
  push:
    branches:
      - 'release/**'
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create or update PR (with token fallback)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PR_TOKEN || github.token }}
          script: |
            const head = context.ref.replace('refs/heads/', '');
            const base = 'main';
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const { data: existing } = await github.rest.pulls.list({ owner, repo, state: 'open', base, head: `${owner}:${head}` });
            if (existing.length > 0) { core.info(`PR already exists: #${existing[0].number}`); return; }

            const title = `Release ${head.replace(/^release\//, '')}`;
            const body = `PR automático generado por workflow para la rama ${head}.`;
            const { data: pr } = await github.rest.pulls.create({ owner, repo, title, head, base, body, draft: false });
            core.info(`PR created: #${pr.number}`);
            try { await github.rest.issues.addLabels({ owner, repo, issue_number: pr.number, labels: ['release'] }); } catch (e) { core.info('Label "release" not added (may not exist).'); }

