name: Deploy to Production (Windows Self‑Hosted)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: deploy-production
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    runs-on:
      - self-hosted
      - windows
      - nioxtec
    timeout-minutes: 30
    steps:
      - name: Preflight – PowerShell policy
        shell: powershell
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force

      - name: Despliegue vía tarea programada (fallback a script)
        shell: cmd
        run: |
          schtasks /Query /TN "Nioxtec Deploy CI" >NUL 2>&1 && (
            schtasks /Run /TN "Nioxtec Deploy CI"
          ) || (
            C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\deploy\deploy_prod.ps1"
          )

      - name: Health‑check API
        shell: powershell
        run: |
          try {
            $code = (Invoke-WebRequest https://api.nioxtec.es/health -UseBasicParsing -TimeoutSec 10).StatusCode
            if ($code -ne 200) { Write-Error "API health returned $code"; exit 1 }
          } catch { Write-Error $_.Exception.Message; exit 1 }


